[github_app]
handle_push_trigger = true
push_commands = [
    [pr_reviewer]
extra_instructions="""\
In the `possible issues` section, emphasize the following:
- Is the code logic efficient?
-
"""
inline_code_comments=true
require_score_review=true
require_can_be_split_review=true
num_code_suggestions="8"

@CodiumAI-Agent /review
auto_approve
--pr_reviewer.extra_instructions="
In the `possible issues` section, emphasize the following:
- Is the code logic efficient?
- 
"
--pr_reviewer.inline_code_comments=true
-i
--pr_reviewer.require_score_review=true
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.num_code_suggestions="8"

[pr_code_suggestions]
extra_instructions="""\
Emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
-
"""
num_code_suggestions_per_chunk="10"
commitable_code_suggestions=true
suggestions_score_threshold="8"

[pr_update_changelog]
push_changelog_changes=true

]