name: action-git-diff-suggestions

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Code Inspector GitHub Action
        uses: bensuperpc/code-inspector@v1.0.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
          code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
          min_quality_grade: 'GOOD'
          min_quality_score: 80
          max_defects_rate: 0.02
          max_complex_functions_rate: 0.1
          max_long_functions_rate: 0.05
          project_name: 'scheduling-beta'
          max_timeout_sec: 600

      - name: Git diff suggestions
        uses: getsentry/action-git-diff-suggestions@main
        with:
          message: 'eslint made the following change'

      - name: Run tests
        run: npm test
